import { Link, useLocation } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { useConsent } from '@/contexts/ConsentContext';

export default function PolicyPage() {
  const cookie = useLocation().pathname.includes('cookie');
  const { openPreferences } = useConsent();
  return <main className="min-h-screen bg-[#fbfaf7] px-4 py-10 text-stone-800"><article className="mx-auto max-w-3xl rounded-2xl border bg-white p-6 shadow-sm sm:p-10"><Link to="/" className="text-sm underline">← Back to Perfurm</Link><h1 className="mt-6 font-serif text-4xl">{cookie ? 'Cookie Policy' : 'Privacy Policy'}</h1><p className="mt-2 text-sm text-stone-500">Version 2026-08-06.1 · Effective 6 August 2026</p>{cookie ? <div className="mt-8 space-y-5 leading-7"><p>Perfurm uses necessary cookies and local storage for secure sign-in, fraud prevention, checkout and the shopping cart. These cannot be switched off because the service would not work correctly.</p><h2 className="text-xl font-semibold">Optional categories</h2><p>Functional storage remembers convenience choices. Analytics measures storefront and campaign performance. Marketing enables campaign measurement and optional media. Personalization supports tailored recommendations. Optional categories remain off until you choose them.</p><h2 className="text-xl font-semibold">Duration and control</h2><p>Your choice lasts up to 180 days and is requested again after a material policy update. Withdrawing consent removes known optional browser identifiers; legal transaction records and necessary security records remain subject to their retention rules.</p><Button onClick={openPreferences}>Manage cookie preferences</Button></div> : <div className="mt-8 space-y-5 leading-7"><p>Perfurm processes account, contact, address, order and payment-reference information to provide shopping, delivery, support, fraud prevention and legal compliance. Card details are handled by the configured payment provider and are not stored by Perfurm.</p><h2 className="text-xl font-semibold">Your choices and rights</h2><p>You can export account data and request deletion in Settings. Depending on applicable law, you may also request access, correction, restriction or objection through care@perfurm.com. Some invoice and transaction records must be retained for legal obligations.</p><h2 className="text-xl font-semibold">Sharing and security</h2><p>Data is shared only with configured processors needed for hosting, payments, shipping and communications, under appropriate contracts. Perfurm applies access controls, encrypted transport, session rotation, audit logging and data minimisation.</p><p>This operational notice requires review by qualified privacy counsel before a production launch.</p></div>}</article></main>;
}
