import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { ChevronLeft, ChevronRight, Gift, Mail, MapPin, Phone, RefreshCw, Search, Settings2, ShoppingBag, UserRound } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { toast } from 'sonner';

const API_URL = process.env.REACT_APP_BACKEND_URL + '/api';
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));

export default function UserManagement() {
  const [items,setItems]=useState([]), [total,setTotal]=useState(0), [page,setPage]=useState(1), [pages,setPages]=useState(1);
  const [filters,setFilters]=useState({q:'',status:'all',city:'',min_orders:'',min_spent:''});
  const [loading,setLoading]=useState(true), [error,setError]=useState(''), [selected,setSelected]=useState(null), [dialog,setDialog]=useState('');
  const [account,setAccount]=useState({status:'disabled',duration_days:'7',reason:''});
  const [credit,setCredit]=useState({amount:'50',product_id:'',reason:'Promotional prepaid credit'});
  const load=useCallback(async()=>{setLoading(true);setError('');try{const p={...filters,status:filters.status==='all'?undefined:filters.status,q:filters.q||undefined,city:filters.city||undefined,min_orders:filters.min_orders||undefined,min_spent:filters.min_spent||undefined,page,page_size:30};const r=await axios.get(`${API_URL}/admin/customers`,{params:p});setItems(r.data.items||[]);setTotal(r.data.total||0);setPages(r.data.pages||1);}catch(e){setError(e.response?.data?.detail||'Unable to load customers');}finally{setLoading(false);}},[filters,page]);
  useEffect(()=>{const timer=setTimeout(load,300);return()=>clearTimeout(timer);},[load]);
  const setFilter=(key,value)=>{setFilters(current=>({...current,[key]:value}));setPage(1);};
  const submitAccount=async()=>{try{await axios.put(`${API_URL}/admin/customers/${selected.id}/account`,{...account,duration_days:account.status==='active'||account.duration_days==='permanent'?null:Number(account.duration_days)});toast.success('Account control updated');setDialog('');load();}catch(e){toast.error(e.response?.data?.detail||'Could not update account');}};
  const submitCredit=async()=>{try{await axios.post(`${API_URL}/admin/customers/${selected.id}/credits`,{amount:Number(credit.amount),product_id:credit.product_id||null,reason:credit.reason});toast.success('Promotional credit added');setDialog('');load();}catch(e){toast.error(e.response?.data?.detail||'Could not add credit');}};
  return <main className="min-h-screen bg-stone-50 px-3 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#7d4956]">Customer intelligence</p><h1 className="display-serif mt-1 text-3xl font-semibold">User Management</h1><p className="mt-1 text-sm text-stone-500">{total} customer accounts, eligibility and account controls</p></div><Button variant="outline" onClick={load}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
    <Card className="mb-5"><CardContent className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-6"><div className="relative md:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400"/><Input className="pl-9" value={filters.q} onChange={e=>setFilter('q',e.target.value)} placeholder="Name, email, mobile or user ID"/></div><Select value={filters.status} onValueChange={v=>setFilter('status',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All accounts</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="disabled">Disabled</SelectItem><SelectItem value="blocked">Blocked</SelectItem></SelectContent></Select><Input value={filters.city} onChange={e=>setFilter('city',e.target.value)} placeholder="City"/><Input type="number" min="0" value={filters.min_orders} onChange={e=>setFilter('min_orders',e.target.value)} placeholder="Min orders"/><Input type="number" min="0" value={filters.min_spent} onChange={e=>setFilter('min_spent',e.target.value)} placeholder="Min spend ₹"/></CardContent></Card>
    {error?<Card><CardContent className="p-10 text-center text-red-700">{error}</CardContent></Card>:loading?<div className="h-48 animate-pulse rounded-xl bg-stone-200"/>:items.length===0?<Card><CardContent className="p-12 text-center"><UserRound className="mx-auto mb-3 h-12 w-12 text-stone-400"/>No matching customers</CardContent></Card>:<div className="grid gap-3">{items.map(c=><Card key={c.id}><CardContent className="p-4 sm:p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{c.name}</h2><Badge variant={c.account_status==='active'?'default':'destructive'}>{c.account_status}</Badge>{c.promotional_credit>0&&<Badge variant="outline">Credit {money(c.promotional_credit)}</Badge>}</div><div className="mt-2 flex flex-col gap-1 text-sm text-stone-500"><span className="flex items-center gap-1"><Mail className="h-4 w-4"/>{c.email}</span><span className="flex items-center gap-1"><Phone className="h-4 w-4"/>{c.phone||'No mobile'}</span><span className="flex items-center gap-1"><MapPin className="h-4 w-4"/>{[c.location?.city,c.location?.state,c.location?.pincode].filter(Boolean).join(', ')||'No location'}</span></div></div><div className="grid grid-cols-2 gap-2 text-center sm:grid-cols-5 xl:w-[520px]"><Metric label="Orders" value={c.order_stats?.total}/><Metric label="Delivered" value={c.order_stats?.delivered}/><Metric label="Cancelled" value={c.order_stats?.cancelled}/><Metric label="Active" value={c.order_stats?.active}/><Metric label="Spent" value={money(c.order_stats?.total_spent)}/></div><div className="flex gap-2 xl:flex-col"><Button size="sm" variant="outline" onClick={()=>{setSelected(c);setDialog('credit');}}><Gift className="mr-1 h-4 w-4"/>Credit</Button><Button size="sm" variant="outline" onClick={()=>{setSelected(c);setAccount({status:c.account_status==='active'?'disabled':'active',duration_days:'7',reason:''});setDialog('account');}}><Settings2 className="mr-1 h-4 w-4"/>Control</Button></div></div></CardContent></Card>)}</div>}
    {pages>1&&<div className="mt-6 flex justify-center gap-3"><Button variant="outline" size="icon" disabled={page<=1} onClick={()=>setPage(v=>v-1)}><ChevronLeft/></Button><span className="py-2 text-sm">Page {page} of {pages}</span><Button variant="outline" size="icon" disabled={page>=pages} onClick={()=>setPage(v=>v+1)}><ChevronRight/></Button></div>}
    <Dialog open={dialog==='account'} onOpenChange={o=>!o&&setDialog('')}><DialogContent><DialogHeader><DialogTitle>Account control — {selected?.name}</DialogTitle></DialogHeader><Label>Status</Label><Select value={account.status} onValueChange={v=>setAccount({...account,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Activate now</SelectItem><SelectItem value="disabled">Temporarily disable</SelectItem><SelectItem value="blocked">Block account</SelectItem></SelectContent></Select>{account.status!=='active'&&<><Label>Time frame</Label><Select value={account.duration_days} onValueChange={v=>setAccount({...account,duration_days:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="7">7 days</SelectItem><SelectItem value="15">15 days</SelectItem><SelectItem value="30">30 days</SelectItem><SelectItem value="60">2 months</SelectItem><SelectItem value="permanent">Until admin activates</SelectItem></SelectContent></Select></>}<Label>Reason *</Label><Input value={account.reason} maxLength={500} onChange={e=>setAccount({...account,reason:e.target.value})} placeholder="Reason shown in audit history"/><DialogFooter><Button onClick={submitAccount} disabled={account.reason.trim().length<3}>Confirm</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={dialog==='credit'} onOpenChange={o=>!o&&setDialog('')}><DialogContent><DialogHeader><DialogTitle>Add prepaid promotional credit — {selected?.name}</DialogTitle></DialogHeader><Label>Amount *</Label><div className="flex gap-2">{[50,100,200].map(v=><Button key={v} type="button" variant={credit.amount===String(v)?'default':'outline'} onClick={()=>setCredit({...credit,amount:String(v)})}>₹{v}</Button>)}</div><Input type="number" min="1" max="100000" value={credit.amount} onChange={e=>setCredit({...credit,amount:e.target.value})}/><Label>Product ID (optional)</Label><Input value={credit.product_id} onChange={e=>setCredit({...credit,product_id:e.target.value})} placeholder="Limit/reference this grant to a product"/><Label>Reason *</Label><Input value={credit.reason} maxLength={300} onChange={e=>setCredit({...credit,reason:e.target.value})}/><DialogFooter><Button onClick={submitCredit} disabled={!Number(credit.amount)||credit.reason.trim().length<3}>Add credit</Button></DialogFooter></DialogContent></Dialog>
  </div></main>;
}
function Metric({label,value}){return <div className="rounded-xl bg-stone-50 p-3"><ShoppingBag className="mx-auto mb-1 h-4 w-4 text-[#7d4956]"/><p className="font-semibold">{value??0}</p><p className="text-[11px] text-stone-500">{label}</p></div>}
